---
- name: Konfigurieren des Load Balancers
  hosts: loadbalancer
  become: yes
  roles:
    - nginx_loadbalancer

- name: Konfigurieren der App-Server
  hosts: app_servers
  become: yes
  roles:
    - nodejs_app


 - name: Beispiel Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: verschlüsselte Variablen
      include_vars:
        file: vars/credentials.yml
        name: credentials
    - name: Debug-Ausgabe der AWS-Credentials
      debug:
        var: credentials

