version: '3' # Die Version hier angeben

services:
  api:
    build: . # Verwendet das lokale Dockerfile zum Erstellen des Images
    ports:
      - "3000:3000" # Port-Mapping für den Service
    environment:
      - MYSQL_HOST=db # Verweist auf den Datenbank-Service
    depends_on:
      - db # Stellt sicher, dass der Datenbank-Service zuerst gestartet wird

  db:
    image: mariadb:11.1.2
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: # Erstellt ein benanntes Volume für die Datenbank
